# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Rut', models.CharField(max_length=20)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
    ]
