# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alarm_api', '0002_auto_20171017_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Rut', models.CharField(max_length=20)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
    ]
